name: weatherapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get: ^4.6.6
  http: ^1.1.0
  intl: ^0.17.0
  provider: ^6.1.1

  sleek_circular_slider: ^2.0.1
  google_maps_flutter: ^2.5.0
  flutter_spinkit: ^5.2.0
  flutter_gif: ^0.0.4
  weather_icons: ^3.0.0
  flutter_map: ^6.0.1
  shared_preferences: ^2.2.2
get: ^4.6.6
http: ^1.1.0
flutter_spinkit: ^5.2.0
flutter_weather_icons: ^1.0.2
flutter_gif: ^0.0.4
dev_dependencies:
  flutter_lints: ^2.0.0
  sqflite: ^2.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animation/.
    - assets/images/.
     
        